### ISSUE TITLE
TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by jamrockmedz** [johannesjo/generator-angular-auto-admin-loopback#7]
Hi, 
I was trying to use this today however when executing "yo aaal" the below TypeError is raised:

```
/usr/lib/node_modules/generator-aaal/app/index.js:13
module.exports = yeoman.Base.extend({
                            ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/generator-aaal/app/index.js:13:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as aaal:app] (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
```

**Comment by johannesjo** [comment]
There was a fix (#5) merged today. Maybe you can try reinstalling the generator?

**Comment by jamrockmedz** [comment]
Thanks for the update, I had to install the generator directly from git:
 npm install -g git+/https://github.com/johannesjo/generator-angular-auto-admin-loopback.git

npm couldn't find the update at the time

```
npm ERR! notarget No compatible version found: generator-aaal@0.0.9
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
```

**Comment by johannesjo** [comment]
Yes I didn't release a new version yet. I will do so! Thanks for reporting back!
